---
dataset_name: "cifar100"
num_classes: 100
batch_size: 50
epochs_per_round: 20
lda_concentration: 0.3
num_clients_per_round: 20
num_total_clients: 100
num_rounds: 10
root_dir: "./data"
cpus_per_client: 1
gpus_per_client: 0
hydra.job.chdir: False

gen_federated_partitions:
  _target_: cifar.utils.gen_cifar100_partitions
  dataset_name: ${dataset_name}
  num_total_clients: ${num_total_clients}
  lda_concentration_coarse: ${lda_concentration}
  lda_concentration_fine: ${lda_concentration

get_initial_parameters:
  _target_: cifar.utils.get_initial_parameters
  num_classes: ${num_classes}

get_eval_fn:
  _target_: cifar.utils.get_cifar_eval_fn
  num_classes: ${num_classes}

gen_on_fit_config_fn:
  _target_: cifar.utils.gen_on_fit_config_fn
  epochs_per_round: ${epochs_per_round}
  batch_size: ${batch_size}
  client_learning_rate_decay: ${strategy.eta_l_decay}
  weight_decay: ${strategy.weight_decay}
  gradient_clipping: ${strategy.gradient_clipping}
  max_norm: ${strategy.max_norm}

plot_results:
  _target_: cifar.utils.plot_metric_from_history
  dataset_name: ${dataset_name}
  strategy_name: ${strategy.name}
  expected_maximum: ${strategy.expected_accuracy}
  save_plot_path: ./${dataset_name}_${strategy.name}.png

get_ray_client_fn:
  _target_: cifar.client.get_ray_client_fn
  fed_dir: None
  num_classes: ${num_classes}

ray_config:
  include_dashboard: False

defaults:
  - _self_
  - strategy: "fedavg"
