---
dataset_name: "femnist"
batch_size: 50
epochs_per_round: 20
num_clients_per_round: 20
num_total_clients: 3230
num_rounds: 2000
root_dir: "./data"
cpus_per_client: 1
gpus_per_client: 0
hydra.job.chdir: False

gen_federated_partitions:
  _target_: femnist.utils.gen_femnist_partitions
  dataset_name: ${dataset_name}

get_initial_parameters:
  _target_: femnist.utils.get_initial_parameters

get_eval_fn:
  _target_: femnist.utils.get_femnist_eval_fn

gen_on_fit_config_fn:
  _target_: femnist.utils.gen_on_fit_config_fn
  epochs_per_round: ${epochs_per_round}
  batch_size: ${batch_size}
  client_learning_rate_decay: ${strategy.eta_l_decay}
  weight_decay: ${strategy.weight_decay}
  gradient_clipping: ${strategy.gradient_clipping}
  max_norm: ${strategy.max_norm}

plot_results:
  _target_: femnist.utils.plot_metric_from_history
  dataset_name: ${dataset_name}
  strategy_name: ${strategy.name}
  expected_maximum: ${strategy.expected_accuracy}
  save_plot_path: ./${dataset_name}_${strategy.name}.png

get_ray_client_fn:
  _target_: femnist.client.get_ray_client_fn
  fed_dir: None

ray_config:
  include_dashboard: False

defaults:
  - _self_
  - strategy: "fedavg"
