---
name: FedProx
expected_accuracy: 49.47
init:
  _target_: flwr.server.strategy.FedProx
  proximal_mu: 0.001
eta_l: 0.01 # client's learning rate
eta_l_decay: 0.998
weight_decay: 0.0001
gradient_clipping: True
max_norm: 10