---
name: FedAvg
expected_accuracy: 72.8
init:
  _target_: flwr.server.strategy.FedAvg
  initial_parameters: None
eta_l: 0.01 # client's learning rate
eta_l_decay: 0.998
weight_decay: 0.0001
gradient_clipping: True
max_norm: 10