---
name: FedAdagrad
expected_accuracy: 80.21
init:
  _target_: flwr.server.strategy.FedAdagrad
  eta: 0.1
  tau: 0
eta_l: 0.01
eta_l_decay: 0.998
weight_decay: 0.0001
gradient_clipping: True
max_norm: 10