num_participating_clients: 10
num_rounds: 10
num_epochs: 20
batch_size: 50
expected_maximum: 0.9924
client_learning_rate: 0.316
client_learning_rate_decay: 0.998
server_learning_rate: 1
proportion_of_test_set_to_use: 0.1
gradient_clipping: True
max_norm: 10
save_path: "C:/Users/henry/Documents/University/Year_3_Part_2/FederatedLearning/flower/baselines/flwr_baselines/publications/fedavg_femnist/docs/results"
run_num: 1