num_participating_clients: 20
num_rounds: 5
num_epochs: 20
batch_size: 50
expected_maximum: 0.9924
client_learning_rate: 0.316
client_learning_rate_decay: 0.998
server_learning_rate: 1
gradient_clipping: True
max_norm: 10
save_path: "docs/results"